plugins {
    id 'java'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'com.vanderis'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url = "https://jitpack.io"
    }
    maven {
        name = "spigotmc-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    flatDir {
        dirs("lib")
    }
}

dependencies {
    compileOnly "org.spigotmc:spigot-api:1.20.6-R0.1-SNAPSHOT"

    implementation 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    implementation "com.github.huynhphap100:Tools-1.3.1a:main-SNAPSHOT"

    implementation("com.github.cryptomorin:XSeries:11.2.1")
}

tasks.jar.configure {
    archiveClassifier = 'default'
}

shadowJar.configure {
    archiveClassifier  = null
}

shadowJar {
    exclude "META-INF"

    dependencies {
        include(dependency('com.vanderis:talismans:1.0-SNAPSHOT'))
        include(dependency('com.github.huynhphap100:Tools-1.3.1a:main-SNAPSHOT'))
    }
}

tasks.register('copyJar', Copy) {
    from shadowJar // copies output of file produced from jar task
    into 'D:/Code Project/Minecraft Coding/TestServer/1.20.6/plugins'
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
