name: Talismans
version: '${version}'
main: com.vanderis.talismans.Talismans
api-version: '1.13'
author: "Vanderis-Team"

commands:
  talismans:
    description: "Command main"
  talisman:
    description: "Command main"